### Hello, World!: localhost:5000
GET http://localhost:5000

### Greeting!: localhost:5000/greets
POST http://localhost:5000/greets
Content-Type: application/json

{
  "name": "John"
}


### Hello, World!: https://flask-hello-1ktu.onrender.com
GET https://flask-hello-1ktu.onrender.com

### Greeting!: https://flask-hello-1ktu.onrender.com/greets
POST https://flask-hello-1ktu.onrender.com/greets
Content-Type: application/json

{
  "name": "John"
}


